
language: node_js 
node_js: - stable 

branches: 
  only: 
    - dev

cache:
  directories:
    - node_modules

install: 
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install
  
  script:
  - hexo clean
  - hexo generate 
  
  after_success: 
  - sed -i'' "s~git@github.com:~https://s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo deploy

notifications:
  email: true
