language: node_js
node_js: stable


install:
  - npm install
  - npm install hexo-generator-searchdb --save

#before_script:

script:
  - hexo clean && hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "rason00"
  - git config user.email "rason00@163..com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branchs:
  only:
    - dev

env:
  global:
    - GH_REF: github.com/rason00/rason00.github.io.git

notifications: # 设置通知项
  email: true
