# .tarvis.yml
language: node_js # 指定语言环境
node_js:
  - "6" # 指定 NodeJS 版本
dist: trusty # 指定系统版本。trusty 是指 Ubuntu 14.04 发行版的名称
sudo: required # 是否需要 sudo 权限

branches: # 指定要构建的分支
  only: # only 表示只构建以下分支
  - writing

install: # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  # 全局安装 Hexo
  - npm install -g hexo
  # 全局安装 Hexo 命令行工具，因为我们是命令行操作
  - npm install -g hexo-cli
  # 安装 package.json 中的依赖
  - npm install

script: # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - hexo clean
  - hexo generate # Hexo 常规命令，执行清理和生成
  - sed -i'' "s~git@github.com:~https://s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml

after_success: # 在构建成功后要运行的命令，构建失败不会执行，其他同上
  - hexo deploy > /dev/null # 通过 hexo 的 deploy 命令部署博客

notifications:
  email: true